openapi: 3.0.0
info:
  title: API Utilisateurs et Contacts
  version: 1.0.0
  description: API de gestion des utilisateurs et des contacts

servers:
  - url: http://localhost:8000/api

paths:
  # ----------- Routes Utilisateurs -----------
  /auth/register:
    post:
      summary: Enregistrer un nouvel utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: Utilisateur créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users:
    get:
      summary: Récupérer tous les utilisateurs
      responses:
        '200':
          description: Liste des utilisateurs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /user/{id}:
    get:
      summary: Récupérer un utilisateur par ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID de l'utilisateur
      responses:
        '200':
          description: Utilisateur trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Utilisateur non trouvé

  /update/user/{id}:
    patch:
      summary: Mettre à jour un utilisateur par ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID de l'utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: Utilisateur mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Utilisateur non trouvé

  /delete/user/{id}:
    delete:
      summary: Supprimer un utilisateur par ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID de l'utilisateur
      responses:
        '200':
          description: Utilisateur supprimé avec succès
        '404':
          description: Utilisateur non trouvé

  # ----------- Routes Contacts -----------
  /contacts:
    get:
      summary: Récupérer tous les contacts
      responses:
        '200':
          description: Liste des contacts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
    post:
      summary: Créer un nouveau contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactInput'
      responses:
        '200':
          description: Contact créé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'

  /contact/{id}:
    get:
      summary: Récupérer un contact par ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID du contact
      responses:
        '200':
          description: Contact trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
        '404':
          description: Contact non trouvé
    patch:
      summary: Mettre à jour un contact par ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID du contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactInput'
      responses:
        '200':
          description: Contact mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
        '404':
          description: Contact non trouvé
    delete:
      summary: Supprimer un contact par ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID du contact
      responses:
        '200':
          description: Contact supprimé avec succès
        '404':
          description: Contact non trouvé

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          example: "60c72b2f9b1d4c3a4f9f8a67"
        username:
          type: string
          example: "sofiane"
        email:
          type: string
          example: "sofiane@example.com"
        # Ajoute d’autres champs si besoin

    UserInput:
      type: object
      properties:
        username:
          type: string
          example: "sofiane"
        email:
          type: string
          example: "sofiane@example.com"
        password:
          type: string
          example: "monMotDePasse123"
      required:
        - username
        - email
        - password

    Contact:
      type: object
      properties:
        _id:
          type: string
          example: "60c72b2f9b1d4c3a4f9f8a67"
        firstName:
          type: string
          example: "Sofiane"
        lastName:
          type: string
          example: "Charrada"
        phone:
          type: string
          example: "+33612345678"

    ContactInput:
      type: object
      properties:
        firstName:
          type: string
          example: "Sofiane"
        lastName:
          type: string
          example: "Charrada"
        phone:
          type: string
          example: "+33612345678"
      required:
        - firstName
        - lastName
        - phone
